# ---------- Builder ----------
FROM registry.access.redhat.com/ubi9/python-312:latest AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# Install MySQL build deps
RUN dnf install -y gcc make mariadb-connector-c-devel pkg-config \
    && dnf clean all

WORKDIR /app
COPY requirements.txt /app/

# Build wheels
RUN python3 -m pip install --upgrade pip wheel \
 && python3 -m pip wheel --wheel-dir /wheels -r requirements.txt


# ---------- Runtime ----------
FROM registry.access.redhat.com/ubi9/python-312:latest AS runtime

RUN dnf install -y mariadb-connector-c-devel && dnf clean all

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY --from=builder /wheels /wheels
RUN python3 -m pip install --no-cache-dir /wheels/* && rm -rf /wheels

COPY --chown=10001:10001 . /app
RUN useradd -u 10001 -M -s /usr/sbin/nologin test

COPY ./executable.sh /app/executable.sh
RUN chmod +x /app/executable.sh

ENTRYPOINT ["/app/executable.sh"]

USER 10001
EXPOSE 8000
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
